definitions:
  models.Role:
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        description: gorm.Model        //默认模型结构体
        type: integer
      role:
        type: string
      updatedAt:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /roles:
    get:
      description: 获取所有角色及其关联权限
      produces:
      - application/json
      responses:
        "200":
          description: 角色列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取角色列表
      tags:
      - Role Management
    post:
      consumes:
      - application/json
      description: 创建一个新角色
      parameters:
      - description: 角色信息
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/models.Role'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功响应
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求体无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 创建角色
      tags:
      - Role Management
  /roles/{id}:
    delete:
      description: 删除指定角色
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 删除成功响应
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 删除角色
      tags:
      - Role Management
    put:
      consumes:
      - application/json
      description: 更新角色信息
      parameters:
      - description: 角色ID
        in: path
        name: id
        required: true
        type: integer
      - description: 角色更新信息
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/models.Role'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功响应
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求体无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 更新角色
      tags:
      - Role Management
  /users/{id}:
    delete:
      description: 删除指定用户
      parameters:
      - description: 用户管理ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 删除成功响应
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 删除用户
      tags:
      - 用户管理
    put:
      consumes:
      - application/json
      description: 更新用户信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 用户更新信息
        in: body
        name: role
        required: true
        schema:
          $ref: '#/definitions/models.Role'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功响应
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求体无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 更新用户
      tags:
      - 用户管理
  /users/creat:
    post:
      consumes:
      - application/json
      description: 创建一个新用户
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功响应
          schema:
            additionalProperties: true
            type: object
        "400":
          description: 请求体无效
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 创建用户
      tags:
      - 用户管理
  /users/get:
    get:
      description: 获取所选页用户
      produces:
      - application/json
      responses:
        "200":
          description: 用户列表
          schema:
            additionalProperties: true
            type: object
        "500":
          description: 服务器错误
          schema:
            additionalProperties: true
            type: object
      summary: 获取用户列表
      tags:
      - 用户管理
swagger: "2.0"
